# Python Programming Basics

In [1]:
# Variables and Data Types
name = "PragyanAI"
age = 2
rating = 4.8
is_active = True

print(name)
print(age)
print(rating)
print(is_active)

# Arithmetic Operations
a = 20
b = 5

print("Addition:", a + b)
print("Subtraction:", a - b)
print("Multiplication:", a * b)
print("Division:", a / b)

# User Input
student_name = input("Enter your name: ")
print("Welcome", student_name)

PragyanAI
2
4.8
True
Addition: 25
Subtraction: 15
Multiplication: 100
Division: 4.0
Enter your name: Pragna 
Welcome Pragna 


In [2]:
a = 15
b = 4

print("Addition:", a + b)
print("Subtraction:", a - b)
print("Multiplication:", a * b)
print("Division:", a / b)
print("Floor Division:", a // b)
print("Modulus:", a % b)
print("Exponent:", a ** b)

Addition: 19
Subtraction: 11
Multiplication: 60
Division: 3.75
Floor Division: 3
Modulus: 3
Exponent: 50625


In [3]:
x = 10

x += 5
print(x)

x -= 2
print(x)

x *= 3
print(x)

x /= 2
print(x)

15
13
39
19.5


In [4]:
a = 20
b = 15

print(a == b)
print(a != b)
print(a > b)
print(a < b)
print(a >= b)
print(a <= b)

False
True
True
False
True
False


In [5]:
age = 22
salary = 50000

print(age > 18 and salary > 30000)
print(age < 18 or salary > 30000)
print(not(age > 18))

True
True
False


In [6]:
a = [1, 2, 3]
b = a
c = [1, 2, 3]

print(a is b)
print(a is c)

print(a is not c)

True
False
True


In [7]:
skills = ["Python", "SQL", "Power BI"]

print("Python" in skills)
print("Java" not in skills)

True
True


In [8]:
a = 5
b = 3

print(a & b)
print(a | b)
print(a ^ b)
print(~a)
print(a << 1)
print(a >> 1)

1
7
6
-6
10
2


Operator Precedence

In [9]:
result = 10 + 5 * 2

print(result)

result2 = (10 + 5) * 2

print(result2)

20
30


In [10]:
marks = 85

result = "Pass" if marks >= 40 else "Fail"

print(result)

Pass


In [11]:
age = 25

print(18 <= age <= 60)

True


In [12]:
numbers = [10, 20, 30]

if (length := len(numbers)) > 2:
    print("Length:", length)

Length: 3


In [13]:
name = input("Enter your name: ")

print("Welcome", name)

Enter your name: pragna
Welcome pragna


In [14]:
age = int(input("Enter age: "))
salary = float(input("Enter salary: "))

print(age)
print(salary)

Enter age: 18
Enter salary: 5000
18
5000.0


In [15]:
a, b = input("Enter two numbers: ").split()

print(a)
print(b)

Enter two numbers: 45 25
45
25


In [16]:
a, b = map(int, input("Enter numbers: ").split())

print("Sum:", a + b)

Enter numbers: 45 25
Sum: 70


In [17]:
numbers = list(map(int, input("Enter numbers: ").split()))

print(numbers)

Enter numbers: 5
[5]


In [21]:
numbers = eval(input("Enter numbers in list format: "))

print(numbers)

Enter numbers in list format: 45
45


In [22]:
print("Python", "SQL", "PowerBI", sep=" | ")

print("Welcome", end=" ")
print("Students")

Python | SQL | PowerBI
Welcome Students


In [23]:
name = "Sateesh"
score = 95

print("Student {} scored {}".format(name, score))

Student Sateesh scored 95


In [24]:
name = "Priya"
salary = 55000

print(f"{name} earns {salary}")

Priya earns 55000


In [25]:
pi = 3.1415926535

print(f"{pi:.2f}")
print(f"{pi:.4f}")

3.14
3.1416


In [26]:
name = "Aman"
marks = 90

print(f"{'Name':<10} {'Marks':<10}")
print(f"{name:<10} {marks:<10}")

Name       Marks     
Aman       90        


In [27]:
value = 0.8567

print(f"{value:.2%}")

85.67%


In [28]:
from pprint import pprint

data = {
    "students": ["Aman", "Priya"],
    "marks": [90, 88]
}

pprint(data)

{'marks': [90, 88], 'students': ['Aman', 'Priya']}


In [29]:
from math import sqrt, factorial

print(sqrt(64))
print(factorial(5))

8.0
120


In [30]:
import random
import datetime
import os

print(random.randint(1, 100))

print(datetime.datetime.now())

print(os.getcwd())

57
2026-06-18 03:17:06.496268
/content


In [31]:
# Install using terminal

#pip install pandas
#pip install numpy
!pip install plotly

Conditional Statements & Loops

In [32]:
# If Else
marks = 85

if marks >= 90:
    print("Grade A")
elif marks >= 75:
    print("Grade B")
else:
    print("Grade C")

# For Loop
for i in range(1, 6):
    print("Number:", i)

# While Loop
count = 1

while count <= 5:
    print("Count:", count)
    count += 1

Grade B
Number: 1
Number: 2
Number: 3
Number: 4
Number: 5
Count: 1
Count: 2
Count: 3
Count: 4
Count: 5


In [34]:
marks = 78

if marks >= 90:
    print("Grade A")

elif marks >= 75:
    print("Grade B")

elif marks >= 50:
    print("Grade C")

else:
    print("Fail")

Grade B


In [35]:
age = 25
salary = 40000

if age >= 18:

    if salary >= 30000:
        print("Eligible for Loan")

    else:
        print("Salary Too Low")

else:
    print("Underage")

Eligible for Loan


In [36]:
# python 3.10+
day = 3

match day:

    case 1:
        print("Monday")

    case 2:
        print("Tuesday")

    case 3:
        print("Wednesday")

    case _:
        print("Invalid Day")

Wednesday


In [37]:
amount = 6000

if amount >= 5000:
    discount = amount * 0.10
    final = amount - discount

    print("Discount:", discount)
    print("Final Amount:", final)

else:
    print("No Discount")

Discount: 600.0
Final Amount: 5400.0


In [38]:
for i in range(1, 6):
    print(i)

1
2
3
4
5


In [40]:
# Start, Stop
for i in range(1, 5):
    print(i)

# Start, Stop, Step
for i in range(0, 10, 2):
    print(i)

1
2
3
4
0
2
4
6
8


In [39]:
students = ["Aman", "Rahul", "Priya"]

for student in students:
    print(student)

Aman
Rahul
Priya


In [41]:
text = "Python"

for char in text:
    print(char)

P
y
t
h
o
n


In [42]:
count = 1

while count <= 5:
    print(count)

    count += 1

1
2
3
4
5


In [43]:
for i in range(1, 10):

    if i == 5:
        break

    print(i)

1
2
3
4


In [ ]:
for i in range(1, 6):

    if i == 3:
        continue

    print(i)

In [44]:
for i in range(1, 5):
    print(i)

else:
    print("Loop Completed")

1
2
3
4
Loop Completed


In [48]:
for i in range(1, 4):

    for j in range(1, 4):

        print(i, j)

1 1
1 2
1 3
2 1
2 2
2 3
3 1
3 2
3 3


In [46]:
number = 17

is_prime = True

for i in range(2, number):

    if number % i == 0:
        is_prime = False
        break

if is_prime:
    print("Prime Number")

else:
    print("Not Prime")

Prime Number


In [47]:
a = 0
b = 1

for i in range(10):

    print(a)

    temp = a
    a = b
    b = temp + b

0
1
1
2
3
5
8
13
21
34


In [49]:
text = "Data Science"

count = 0

for char in text.lower():

    if char in "aeiou":
        count += 1

print("Vowels:", count)

Vowels: 5


In [50]:
for i in range(5, 0, -1):

    print("*" * i)

*****
****
***
**
*


In [51]:
for i in range(1, 6):

    for j in range(1, i + 1):

        print(j, end=" ")

    print()

1 
1 2 
1 2 3 
1 2 3 4 
1 2 3 4 5 


In [52]:
numbers = [1,2,3,4,5,6]

even = [x for x in numbers if x % 2 == 0]

print(even)

[2, 4, 6]


In [53]:
matrix = [[1,2,3],[4,5,6]]

flatten = [item for row in matrix for item in row]

print(flatten)

[1, 2, 3, 4, 5, 6]


In [54]:
students = ["Aman", "Priya", "Rahul"]

for index, name in enumerate(students):

    print(index, name)

0 Aman
1 Priya
2 Rahul


In [55]:
names = ["Aman", "Rahul"]
marks = [90, 85]

for name, score in zip(names, marks):

    print(name, score)

Aman 90
Rahul 85


In [56]:
student = {
    "name": "Aman",
    "marks": 90,
    "city": "Bangalore"
}

for key, value in student.items():

    print(key, value)

name Aman
marks 90
city Bangalore


In [57]:
text = "Python Programming"

print(text)
print(type(text))

#String Indexing

#Each character has a position.

text = "Python"

print(text[0])
print(text[1])
print(text[-1])

#String Slicing
text = "DataScience"

print(text[0:4])
print(text[4:])
print(text[:4])
print(text[-3:])
print(text[::2])
print(text[::-1])

#Important String Functions
#upper() & lower()
text = "Python"

print(text.upper())
print(text.lower())
#strip()
text = "   Data Analytics   "

print(text.strip())
#replace()
text = "I love Java"

print(text.replace("Java", "Python"))
#split()
text = "Python,SQL,PowerBI"

skills = text.split(",")

print(skills)
#join()
skills = ["Python", "SQL", "AI"]

result = " | ".join(skills)

print(result)
#find()
text = "Machine Learning"

print(text.find("Learning"))
#count()
text = "python python ai"

print(text.count("python"))
#startswith() & endswith()
text = "analytics.csv"

print(text.startswith("analytics"))
print(text.endswith(".csv"))
#isdigit(), isalpha(), isalnum()
print("123".isdigit())
print("Python".isalpha())
print("Python123".isalnum())
#String Programs
#Reverse String
text = "Python"

print(text[::-1])
#Palindrome Checker
text = "madam"

if text == text[::-1]:
    print("Palindrome")

else:
    print("Not Palindrome")

Python Programming
<class 'str'>
P
y
n
Data
Science
Data
nce
DtSine
ecneicSataD
PYTHON
python
Data Analytics
I love Python
['Python', 'SQL', 'PowerBI']
Python | SQL | AI
8
2
True
True
True
True
True
nohtyP
Palindrome


In [58]:
text = "python"

freq = {}

for char in text:

    freq[char] = freq.get(char, 0) + 1

print(freq)

{'p': 1, 'y': 1, 't': 1, 'h': 1, 'o': 1, 'n': 1}


In [59]:
students = ["Aman", "Rahul", "Priya"]

print(students)
#List Indexing & Slicing
numbers = [10,20,30,40,50]

print(numbers[0])
print(numbers[-1])

print(numbers[1:4])
print(numbers[::-1])
#Important List Functions
#append()
numbers = [1,2,3]

numbers.append(4)

print(numbers)
#extend()
a = [1,2]
b = [3,4]

a.extend(b)

print(a)
#insert()
numbers = [1,2,4]

numbers.insert(2, 3)

print(numbers)
#remove()
numbers = [1,2,3,4]

numbers.remove(3)

print(numbers)
#pop()
numbers = [10,20,30]

numbers.pop()

print(numbers)
#sort()
numbers = [5,2,8,1]

numbers.sort()

print(numbers)
#reverse()
numbers = [1,2,3]

numbers.reverse()

print(numbers)
#count()
numbers = [1,1,2,3]

print(numbers.count(1))
#index()
numbers = [10,20,30]

print(numbers.index(20))

['Aman', 'Rahul', 'Priya']
10
50
[20, 30, 40]
[50, 40, 30, 20, 10]
[1, 2, 3, 4]
[1, 2, 3, 4]
[1, 2, 3, 4]
[1, 2, 4]
[10, 20]
[1, 2, 5, 8]
[3, 2, 1]
2
1


In [ ]:
matrix = [
    [1,2,3],
    [4,5,6]
]

print(matrix[0][1])

# Tuple

In [60]:
data = (10,20,30)

print(data)

(10, 20, 30)


In [61]:
#Tuple Indexing & Slicing
numbers = (1,2,3,4,5)

print(numbers[0])
print(numbers[1:4])

1
(2, 3, 4)


In [62]:
#Tuple Functions
#count()
numbers = (1,1,2,3)

print(numbers.count(1))
#index()
numbers = (10,20,30)

print(numbers.index(20))
#Tuple Packing & Unpacking
student = ("Aman", 90)

name, marks = student

print(name)
print(marks)

2
1
Aman
90


## Set

In [71]:
numbers = {1,2,3,3,4}

print(numbers)

{1, 2, 3, 4}


In [72]:
#Set Functions
#add()
numbers = {1,2,3}

numbers.add(4)

print(numbers)

{1, 2, 3, 4}


In [73]:
#remove()
numbers = {1,2,3}

numbers.remove(2)

print(numbers)

{1, 3}


In [74]:
#union()
a = {1,2,3}
b = {3,4,5}

print(a.union(b))

{1, 2, 3, 4, 5}


In [75]:
#intersection()
a = {1,2,3}
b = {2,3,4}

print(a.intersection(b))

{2, 3}


In [76]:
#difference()
a = {1,2,3}
b = {2,3}
print(a.difference(b))

{1}


In [77]:
#Set Programs
#Remove Duplicate Values
numbers = [1,1,2,3,4,4]
unique = set(numbers)
print(unique)

{1, 2, 3, 4}


In [78]:
#Common Elements
a = {1,2,3}
b = {2,3,4}
print(a & b)

{2, 3}


#DICTIONARIES IN PYTHON

In [79]:
#Dictionaries store key-value pairs.

student = {
    "name": "Pragyan",
    "marks": 90
}

print(student)

{'name': 'Pragyan', 'marks': 90}


In [80]:
#Access Dictionary Values
student = {
    "name": "Rahul",
    "marks": 85
}

print(student["name"])
print(student.get("marks"))

Rahul
85


In [81]:
#Dictionary Functions
#keys()
student = {
    "name": "Pragyan",
    "marks": 90
}

print(student.keys())
#values()
student = {
    "name": "Pragyan",
    "marks": 90
}

print(student.values())
#items()
student = {
    "name": "Pragyan",
    "marks": 90
}
print(student.items())

dict_keys(['name', 'marks'])
dict_values(['Pragyan', 90])
dict_items([('name', 'Pragyan'), ('marks', 90)])


In [82]:
#update()
student = {
    "name": "Pragyan"
}

student.update({"marks": 95})

print(student)

{'name': 'Pragyan', 'marks': 95}


In [83]:
#pop()
student = {
    "name": "Pragyan",
    "marks": 90
}

student.pop("marks")

print(student)

{'name': 'Pragyan'}


In [84]:
#Dictionary Looping
student = {
    "name": "Aman",
    "marks": 90
}

for key, value in student.items():

    print(key, value)

name Aman
marks 90


In [85]:
#Dictionary Programs
#Word Frequency Counter
text = "python ai python data"

words = text.split()

freq = {}

for word in words:

    freq[word] = freq.get(word, 0) + 1

print(freq)

{'python': 2, 'ai': 1, 'data': 1}


In [86]:
#Student Marks System
students = {
    "Aman": 90,
    "Rahul": 70,
    "Priya": 88
}

topper = max(students, key=students.get)

print(topper)

Aman


# Functions

In [87]:
def greet():

    print("Welcome")

greet()

Welcome


In [88]:
#Function with Parameters
def add(a, b):

    return a + b

print(add(10, 20))

30


In [89]:
#Default Parameters
def student(name, course="Python"):

    print(name, course)

student("Aman")

Aman Python


In [90]:
#Keyword Arguments
def employee(name, salary):

    print(name, salary)

employee(salary=50000, name="Rahul")

Rahul 50000


In [91]:
#Variable Length Arguments
#*args
def total(*numbers):

    print(sum(numbers))

total(1,2,3,4)

10


In [92]:
#**kwargs
def student(**data):

    print(data)

student(name="Aman", marks=90)
#Lambda Functions
square = lambda x: x * x

print(square(5))

{'name': 'Aman', 'marks': 90}
25


In [93]:
#Recursive Function
#Factorial
def factorial(n):

    if n == 1:
        return 1

    return n * factorial(n - 1)

print(factorial(5))

120


In [94]:
#Scope of Variables
x = 100

def test():

    x = 50
    print(x)

test()

print(x)

50
100


In [95]:
#Map Function
numbers = [1,2,3,4]

result = list(map(lambda x: x*2, numbers))

print(result)

[2, 4, 6, 8]


In [96]:
#Filter Function
numbers = [1,2,3,4,5,6]

even = list(filter(lambda x: x % 2 == 0, numbers))

print(even)

[2, 4, 6]


In [97]:
#Reduce Function
from functools import reduce

numbers = [1,2,3,4]

result = reduce(lambda a,b: a+b, numbers)

print(result)

10


# Exceptional Handling

In [98]:
try:
    number = int(input("Enter Number: "))
    print(number)

except:
    print("Invalid Input")

Enter Number: 45
45


# Specific Exception Handling

In [102]:
try:
    a = 10
    b = 0

    print(a / b)

except ZeroDivisionError:
    print("Cannot Divide by Zero")

Cannot Divide by Zero


Multiple Exceptions

In [103]:
try:
    number = int(input("Enter Number: "))
    result = 100 / number

    print(result)

except ValueError:
    print("Invalid Integer")

except ZeroDivisionError:
    print("Division by Zero Not Allowed")

Enter Number: 475
0.21052631578947367


#else Block

In [104]:
try:
    number = int(input("Enter Number: "))

except ValueError:
    print("Invalid Input")

else:
    print("You Entered:", number)

Enter Number: 45
You Entered: 45


#finally Block

In [105]:
try:
    file = open("sample.txt", "r")

except FileNotFoundError:
    print("File Not Found")

finally:
    print("Execution Completed")

File Not Found
Execution Completed


Raising Custom Exceptions

In [108]:
age = -5
if age < 0:
    raise ValueError("Age Cannot Be Negative")

ValueError: Age Cannot Be Negative

#Custom Exception Class

In [109]:
class InvalidMarksError(Exception):
    pass

marks = -10

if marks < 0:
    raise InvalidMarksError("Marks Cannot Be Negative")

InvalidMarksError: Marks Cannot Be Negative

In [117]:
#To avoid the error message, handle it with try-except:
class InvalidMarksError(Exception):
    pass

marks = -10

try:
    if marks < 0:
        raise InvalidMarksError("Marks Cannot Be Negative")
    print("Valid Marks:", marks)

except InvalidMarksError as e:
    print("Error:", e)

Error: Marks Cannot Be Negative


# Exception Handling with Functions

In [110]:
def divide(a, b):

    try:
        return a / b

    except ZeroDivisionError:
        return "Cannot Divide by Zero"

print(divide(10, 0))

Cannot Divide by Zero


#Real-Time Example – ATM

In [111]:
balance = 5000

try:
    amount = int(input("Enter Withdrawal Amount: "))

    if amount > balance:
        raise Exception("Insufficient Balance")

    balance -= amount

    print("Remaining Balance:", balance)

except Exception as e:
    print(e)

Enter Withdrawal Amount: 200
Remaining Balance: 4800


#Real-Time Example – Login System

In [112]:
correct_password = "python123"

try:
    password = input("Enter Password: ")

    if password != correct_password:
        raise Exception("Wrong Password")

    print("Login Successful")

except Exception as e:
    print(e)

Enter Password: pra452
Wrong Password


# FILE HANDLING IN PYTHON

- File handling is used to read/write data into files.

- Opening a File

In [115]:
file = open("sample.txt", "r")

print(file.read())

file.close()

FileNotFoundError: [Errno 2] No such file or directory: 'sample.txt'

In [119]:
try:
    with open("sample.txt", "r") as file:
        print(file.read())
except FileNotFoundError:
    print("Error: sample.txt file not found.")

Error: sample.txt file not found.


File Modes
Mode	Purpose
r	Read
w	Write
a	Append
x	Create
rb	Read Binary
wb	Write Binary
Writing into File

In [ ]:
file = open("sample.txt", "w")

file.write("Welcome to Python")

file.close()

In [120]:
#Appending Data
file = open("sample.txt", "a")

file.write("\nData Analytics")

file.close()

In [121]:
#Reading File Line by Line
file = open("sample.txt", "r")

for line in file:
    print(line)

file.close()



Data Analytics


In [122]:
#Using with Statement (Best Practice)
with open("sample.txt", "r") as file:

    content = file.read()

    print(content)


Data Analytics


In [123]:
#Reading Specific Characters
with open("sample.txt", "r") as file:

    print(file.read(10))
    print(file.read(10))



Data Anal
ytics


#file.readline()

In [124]:
with open("sample.txt", "r") as file:

    print(file.readline())

#readlines()

In [125]:
with open("sample.txt", "r") as file:

    lines = file.readlines()

print(lines)

['\n', 'Data Analytics']


# File Pointer Functions
tell()

In [126]:
with open("sample.txt", "r") as file:

    print(file.tell())

    file.read(5)

    print(file.tell())

0
5


In [127]:
#seek()
with open("sample.txt", "r") as file:

    file.seek(5)

    print(file.read())

 Analytics


In [128]:
#Working with CSV Files
import csv

data = [
    ["Name", "Marks"],
    ["Aman", 90],
    ["Priya", 88]
]

with open("students.csv", "w", newline="") as file:

    writer = csv.writer(file)

    writer.writerows(data)

In [129]:
#Reading CSV
import csv

with open("students.csv", "r") as file:

    reader = csv.reader(file)

    for row in reader:
        print(row)

['Name', 'Marks']
['Aman', '90']
['Priya', '88']


# JSON File Handling
Writing JSON

In [130]:
import json

student = {
    "name": "Aman",
    "marks": 90
}

with open("student.json", "w") as file:

    json.dump(student, file)

Reading JSON

In [131]:
import json

with open("student.json", "r") as file:

    data = json.load(file)

print(data)

{'name': 'Aman', 'marks': 90}


Binary File Handling


In [196]:
from google.colab import files

uploaded = files.upload()

Saving HSR.jpg to HSR.jpg


In [197]:
with open("HSR.jpg", "rb") as file:

    data = file.read()
    print

print(type(data))

<class 'bytes'>


# OBJECT ORIENTED PROGRAMMING (OOPs)

OOPs organizes code using classes and objects.

Creating a Class

In [139]:
class Student:

    pass

s1 = Student()
print(type(s1))

<class '__main__.Student'>


Constructor (init)

In [140]:
class Student:

    def __init__(self, name, marks):

        self.name = name
        self.marks = marks

student1 = Student("Aman", 90)

print(student1.name)
print(student1.marks)

Aman
90


Instance Methods

In [141]:
class Student:

    def __init__(self, name, marks):

        self.name = name
        self.marks = marks

    def display(self):

        print(self.name)
        print(self.marks)

s1 = Student("Rahul", 85)

s1.display()

Rahul
85


Encapsulation


In [142]:
class Bank:

    def __init__(self):

        self.__balance = 5000

    def show_balance(self):

        print(self.__balance)

b1 = Bank()

b1.show_balance()

5000


Inheritance

In [143]:
class Person:

    def display(self):

        print("Person Class")

class Student(Person):

    pass

s1 = Student()

s1.display()

Person Class


In [144]:
#Method Overriding

In [145]:
class Animal:

    def sound(self):

        print("Animal Sound")

class Dog(Animal):

    def sound(self):

        print("Dog Barks")

d1 = Dog()

d1.sound()

Dog Barks


super() Function

In [146]:
class Person:

    def __init__(self, name):

        self.name = name

class Student(Person):

    def __init__(self, name, marks):

        super().__init__(name)

        self.marks = marks

s1 = Student("Aman", 90)

print(s1.name)

Aman


Polymorphism

In [147]:
class Cat:

    def sound(self):

        print("Meow")

class Dog:

    def sound(self):

        print("Bark")

animals = [Cat(), Dog()]

for animal in animals:

    animal.sound()

Meow
Bark


In [148]:
#Abstraction
from abc import ABC, abstractmethod

class Vehicle(ABC):

    @abstractmethod
    def start(self):
        pass

class Car(Vehicle):

    def start(self):
        print("Car Started")

c1 = Car()

c1.start()

Car Started


In [149]:
#Static Method
class Math:

    @staticmethod
    def add(a, b):

        return a + b

print(Math.add(10, 20))

30


In [150]:
#Class Method
class Student:

    school = "PragyanAI"

    @classmethod
    def get_school(cls):

        return cls.school

print(Student.get_school())

PragyanAI


In [151]:
#Operator Overloading
class Number:

    def __init__(self, value):

        self.value = value

    def __add__(self, other):

        return self.value + other.value

n1 = Number(10)
n2 = Number(20)

print(n1 + n2)

30


In [152]:
#Real-Time Example – Employee Management System
class Employee:

    company = "PragyanAI"

    def __init__(self, name, salary):

        self.name = name
        self.salary = salary

    def display(self):

        print("Name:", self.name)
        print("Salary:", self.salary)

e1 = Employee("Rahul", 50000)

e1.display()

Name: Rahul
Salary: 50000


In [153]:
#Real-Time Example – Banking System
class BankAccount:

    def __init__(self, name, balance):

        self.name = name
        self.balance = balance

    def deposit(self, amount):

        self.balance += amount

    def withdraw(self, amount):

        if amount <= self.balance:

            self.balance -= amount

        else:
            print("Insufficient Balance")

    def show_balance(self):

        print(self.balance)

account = BankAccount("Aman", 10000)

account.deposit(5000)

account.withdraw(3000)

account.show_balance()

12000


# PYTHON WITH SQL (SQLite)

In [154]:
import sqlite3

# Create Database
conn = sqlite3.connect("students.db")

print("Database Created")

Database Created


In [155]:
import sqlite3

conn = sqlite3.connect("students.db")

cursor = conn.cursor()

cursor.execute("""
CREATE TABLE IF NOT EXISTS students (
    id INTEGER PRIMARY KEY,
    name TEXT,
    marks INTEGER,
    city TEXT
)
""")

conn.commit()

print("Table Created")

Table Created


In [156]:
import sqlite3

conn = sqlite3.connect("students.db")

cursor = conn.cursor()

query = """
INSERT INTO students(name, marks, city)
VALUES (?, ?, ?)
"""

cursor.execute(query, ("Aman", 90, "Bangalore"))

conn.commit()

print("Record Inserted")

Record Inserted


In [157]:
import sqlite3

conn = sqlite3.connect("students.db")

cursor = conn.cursor()

students = [
    ("Rahul", 85, "Mumbai"),
    ("Priya", 92, "Delhi"),
    ("Kiran", 88, "Hyderabad")
]

query = """
INSERT INTO students(name, marks, city)
VALUES (?, ?, ?)
"""

cursor.executemany(query, students)

conn.commit()

print("Multiple Records Inserted")

Multiple Records Inserted


In [158]:
import sqlite3

conn = sqlite3.connect("students.db")

cursor = conn.cursor()

cursor.execute("SELECT * FROM students")

rows = cursor.fetchall()

for row in rows:
    print(row)

(1, 'Aman', 90, 'Bangalore')
(2, 'Rahul', 85, 'Mumbai')
(3, 'Priya', 92, 'Delhi')
(4, 'Kiran', 88, 'Hyderabad')


In [159]:
import sqlite3

conn = sqlite3.connect("students.db")

cursor = conn.cursor()

cursor.execute("SELECT name, marks FROM students")

data = cursor.fetchall()

print(data)

[('Aman', 90), ('Rahul', 85), ('Priya', 92), ('Kiran', 88)]


In [160]:
import sqlite3

conn = sqlite3.connect("students.db")

cursor = conn.cursor()

query = """
SELECT * FROM students
WHERE marks > 85
"""

cursor.execute(query)

rows = cursor.fetchall()

for row in rows:
    print(row)

(1, 'Aman', 90, 'Bangalore')
(3, 'Priya', 92, 'Delhi')
(4, 'Kiran', 88, 'Hyderabad')


In [161]:
import sqlite3

conn = sqlite3.connect("students.db")

cursor = conn.cursor()

query = """
SELECT * FROM students
ORDER BY marks DESC
"""

cursor.execute(query)

rows = cursor.fetchall()

print(rows)

[(3, 'Priya', 92, 'Delhi'), (1, 'Aman', 90, 'Bangalore'), (4, 'Kiran', 88, 'Hyderabad'), (2, 'Rahul', 85, 'Mumbai')]


In [162]:
import sqlite3

conn = sqlite3.connect("students.db")

cursor = conn.cursor()

query = """
UPDATE students
SET marks = 95
WHERE name = 'Rahul'
"""

cursor.execute(query)

conn.commit()

print("Record Updated")

Record Updated


In [163]:
import sqlite3

conn = sqlite3.connect("students.db")

cursor = conn.cursor()

query = """
DELETE FROM students
WHERE name = 'Kiran'
"""

cursor.execute(query)

conn.commit()

print("Record Deleted")

Record Deleted


In [164]:
import sqlite3

conn = sqlite3.connect("students.db")

cursor = conn.cursor()

query = """
SELECT AVG(marks), MAX(marks), MIN(marks)
FROM students
"""

cursor.execute(query)

result = cursor.fetchone()

print(result)

(92.33333333333333, 95, 90)


SQL with Pandas

In [165]:
import sqlite3
import pandas as pd

conn = sqlite3.connect("students.db")

query = "SELECT * FROM students"

df = pd.read_sql(query, conn)

print(df)

   id   name  marks       city
0   1   Aman     90  Bangalore
1   2  Rahul     95     Mumbai
2   3  Priya     92      Delhi


Export SQL Data to CSV

In [166]:
import sqlite3
import pandas as pd

conn = sqlite3.connect("students.db")

df = pd.read_sql("SELECT * FROM students", conn)

df.to_csv("students_export.csv", index=False)

print("CSV Exported")

CSV Exported


Real-Time Example – Sales Database

In [167]:
import sqlite3

conn = sqlite3.connect("sales.db")

cursor = conn.cursor()

cursor.execute("""
CREATE TABLE IF NOT EXISTS sales (
    id INTEGER PRIMARY KEY,
    product TEXT,
    amount INTEGER
)
""")

sales_data = [
    ("Laptop", 50000),
    ("Mobile", 30000),
    ("Tablet", 20000)
]

cursor.executemany(
    "INSERT INTO sales(product, amount) VALUES (?, ?)",
    sales_data
)

conn.commit()

cursor.execute("""
SELECT SUM(amount)
FROM sales
""")

print("Total Sales:", cursor.fetchone()[0])

Total Sales: 100000


JOIN Example

In [168]:
import sqlite3

conn = sqlite3.connect("company.db")

cursor = conn.cursor()

# Employee Table
cursor.execute("""
CREATE TABLE IF NOT EXISTS employees (
    emp_id INTEGER,
    name TEXT,
    dept_id INTEGER
)
""")

# Department Table
cursor.execute("""
CREATE TABLE IF NOT EXISTS departments (
    dept_id INTEGER,
    dept_name TEXT
)
""")

# Insert Data
cursor.execute("INSERT INTO employees VALUES (1, 'Aman', 101)")
cursor.execute("INSERT INTO departments VALUES (101, 'Data Science')")

conn.commit()

query = """
SELECT employees.name, departments.dept_name
FROM employees
INNER JOIN departments
ON employees.dept_id = departments.dept_id
"""

cursor.execute(query)

print(cursor.fetchall())

[('Aman', 'Data Science')]


MONGODB IN GOOGLE COLAB

In [169]:
!apt-get update
!apt-get install -y gnupg curl
!curl -fsSL https://pgp.mongodb.com/server-7.0.asc | \
gpg -o /usr/share/keyrings/mongodb-server-7.0.gpg \
--dearmor
#!apt-get install -y mongodb

Get:1 https://cloud.r-project.org/bin/linux/ubuntu jammy-cran40/ InRelease [3,632 B]
Get:2 http://security.ubuntu.com/ubuntu jammy-security InRelease [129 kB]
Get:3 https://cli.github.com/packages stable InRelease [3,917 B]
Get:4 https://r2u.stat.illinois.edu/ubuntu jammy InRelease [6,555 B]
Get:5 https://cli.github.com/packages stable/main amd64 Packages [354 B]
Get:6 https://ppa.launchpadcontent.net/deadsnakes/ppa/ubuntu jammy InRelease [18.1 kB]
Hit:7 http://archive.ubuntu.com/ubuntu jammy InRelease
Get:8 https://r2u.stat.illinois.edu/ubuntu jammy/main amd64 Packages [3,062 kB]
Get:9 http://security.ubuntu.com/ubuntu jammy-security/main amd64 Packages [4,026 kB]
Hit:10 https://ppa.launchpadcontent.net/ubuntugis/ppa/ubuntu jammy InRelease
Get:11 http://archive.ubuntu.com/ubuntu jammy-updates InRelease [128 kB]
Get:12 http://security.ubuntu.com/ubuntu jammy-security/restricted amd64 Packages [7,221 kB]
Get:13 http://security.ubuntu.com/ubuntu jammy-security/universe amd64 Packages [1,

In [170]:
!echo "deb [ signed-by=/usr/share/keyrings/mongodb-server-7.0.gpg ] \
https://repo.mongodb.org/apt/ubuntu jammy/mongodb-org/7.0 multiverse" | \
tee /etc/apt/sources.list.d/mongodb-org-7.0.list

deb [ signed-by=/usr/share/keyrings/mongodb-server-7.0.gpg ]  https://repo.mongodb.org/apt/ubuntu jammy/mongodb-org/7.0 multiverse


In [171]:
!apt-get update

Hit:1 https://cloud.r-project.org/bin/linux/ubuntu jammy-cran40/ InRelease
Hit:2 https://cli.github.com/packages stable InRelease
Hit:3 http://security.ubuntu.com/ubuntu jammy-security InRelease
Get:4 https://repo.mongodb.org/apt/ubuntu jammy/mongodb-org/7.0 InRelease [3,005 B]
Hit:5 http://archive.ubuntu.com/ubuntu jammy InRelease
Hit:6 https://r2u.stat.illinois.edu/ubuntu jammy InRelease
Hit:7 http://archive.ubuntu.com/ubuntu jammy-updates InRelease
Get:8 https://repo.mongodb.org/apt/ubuntu jammy/mongodb-org/7.0/multiverse amd64 Packages [120 kB]
Hit:9 https://ppa.launchpadcontent.net/deadsnakes/ppa/ubuntu jammy InRelease
Hit:10 http://archive.ubuntu.com/ubuntu jammy-backports InRelease
Hit:11 https://ppa.launchpadcontent.net/ubuntugis/ppa/ubuntu jammy InRelease
Fetched 123 kB in 1s (109 kB/s)
Reading package lists... Done
W: Skipping acquire of configured file 'main/source/Sources' as repository 'https://r2u.stat.illinois.edu/ubuntu jammy InRelease' does not seem to provide it (sour

In [172]:
!apt-get install -y mongodb-org

Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following additional packages will be installed:
  mongodb-database-tools mongodb-mongosh mongodb-org-database
  mongodb-org-database-tools-extra mongodb-org-mongos mongodb-org-server
  mongodb-org-shell mongodb-org-tools
The following NEW packages will be installed:
  mongodb-database-tools mongodb-mongosh mongodb-org mongodb-org-database
  mongodb-org-database-tools-extra mongodb-org-mongos mongodb-org-server
  mongodb-org-shell mongodb-org-tools
0 upgraded, 9 newly installed, 0 to remove and 41 not upgraded.
Need to get 189 MB of archives.
After this operation, 633 MB of additional disk space will be used.
Get:1 https://repo.mongodb.org/apt/ubuntu jammy/mongodb-org/7.0/multiverse amd64 mongodb-database-tools amd64 100.17.0 [60.7 MB]
Get:2 https://repo.mongodb.org/apt/ubuntu jammy/mongodb-org/7.0/multiverse amd64 mongodb-mongosh amd64 2.8.3 [64.3 MB]
Get:3 https://repo.mongodb.org/apt

In [173]:
!mongod --version

db version v7.0.37
Build Info: {
    "version": "7.0.37",
    "gitVersion": "9d30419d900008ba3ecf2a14546b236f2158b65b",
    "openSSLVersion": "OpenSSL 3.0.2 15 Mar 2022",
    "modules": [],
    "allocator": "tcmalloc",
    "environment": {
        "distmod": "ubuntu2204",
        "distarch": "x86_64",
        "target_arch": "x86_64"
    }
}


In [174]:
!mkdir -p /data/db

In [175]:
!mongod --dbpath /data/db --bind_ip 127.0.0.1 --fork --logpath /tmp/mongodb.log

about to fork child process, waiting until server is ready for connections.
forked process: 8676
child process started successfully, parent exiting


In [176]:
!ps -ef | grep mongod

root        8676       1 83 03:33 ?        00:00:00 mongod --dbpath /data/db --bind_ip 127.0.0.1 --fork --logpath /tmp/mongodb.log
root        8719    2591  0 03:33 ?        00:00:00 /bin/bash -c ps -ef | grep mongod
root        8721    8719  0 03:33 ?        00:00:00 grep mongod


In [177]:
!pip install pymongo
!pip install dnspython

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.8/1.8 MB 9.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 331.1/331.1 kB 19.1 MB/s eta 0:00:00


In [178]:
from pymongo import MongoClient

client = MongoClient("mongodb://127.0.0.1:27017/")

print("MongoDB Connected Successfully")

MongoDB Connected Successfully


In [179]:
db = client["analytics_db"]

collection = db["students"]

print("Database and Collection Created")

Database and Collection Created


In [180]:
student = {
    "name": "Aman",
    "marks": 90,
    "city": "Bangalore"
}

collection.insert_one(student)

print("Document Inserted")

Document Inserted


In [181]:
for doc in collection.find():

    print(doc)

{'_id': ObjectId('6a33670a9781aff169c219c2'), 'name': 'Aman', 'marks': 90, 'city': 'Bangalore'}


In [182]:
students = [
    {
        "name": "Rahul",
        "marks": 85
    },

    {
        "name": "Priya",
        "marks": 92
    }
]

collection.insert_many(students)

print("Multiple Documents Inserted")

Multiple Documents Inserted


In [183]:
query = {
    "marks": {"$gt": 85}
}

results = collection.find(query)

for doc in results:

    print(doc)

{'_id': ObjectId('6a33670a9781aff169c219c2'), 'name': 'Aman', 'marks': 90, 'city': 'Bangalore'}
{'_id': ObjectId('6a33670a9781aff169c219c4'), 'name': 'Priya', 'marks': 92}


In [184]:
import pandas as pd

data = list(collection.find())

df = pd.DataFrame(data)

print(df)

                        _id   name  marks       city
0  6a33670a9781aff169c219c2   Aman     90  Bangalore
1  6a33670a9781aff169c219c3  Rahul     85        NaN
2  6a33670a9781aff169c219c4  Priya     92        NaN


In [185]:
df.to_csv("students.csv", index=False)

print("CSV Exported")

CSV Exported


In [186]:
!pkill mongod

##ERRORs

1. SYNTAX ERRORS

Syntax errors occur when Python rules are violated.

In [201]:
#Missing Colon Error
if 5 > 2
    print("Hello")

SyntaxError: expected ':' (609520067.py, line 2)

In [202]:
#Correct Code
if 5 > 2:
    print("Hello")

Hello


In [225]:
#Indentation Error
def test():
print("Python")

IndentationError: expected an indented block after function definition on line 2 (2490021044.py, line 3)

In [204]:
#Correct Code
def test():
    print("Python")

In [205]:
#Missing Bracket Error
numbers = [1, 2, 3

SyntaxError: incomplete input (2751625708.py, line 2)

In [226]:
numbers = [1, 2, 3]

In [207]:
#Invalid Assignment
10 = x

SyntaxError: cannot assign to literal here. Maybe you meant '==' instead of '='? (272448865.py, line 2)

In [ ]:
x = 10

In [208]:
#Wrong Keyword Usage
class = "Python"

SyntaxError: invalid syntax (2594820956.py, line 2)

2. RUNTIME ERRORS (EXCEPTIONS)
These occur during execution.


In [209]:
#NameError

#Occurs when variable is not defined.

print(name)

Aman


In [210]:
#Correct Code
name = "Aman"

print(name)

Aman


In [211]:
#TypeError

#Occurs when incompatible data types are used.

print(10 + "20")

TypeError: unsupported operand type(s) for +: 'int' and 'str'

In [ ]:
#Correct Code
print(10 + int("20"))

In [212]:
#ValueError

#Occurs when correct type but invalid value is used.

number = int("abc")

ValueError: invalid literal for int() with base 10: 'abc'

In [213]:
#Correct Code
print(10 + int("20"))

30


In [214]:
#IndexError

#Occurs when index is out of range.

numbers = [1,2,3]

print(numbers[5])

IndexError: list index out of range

In [215]:
print(numbers[2])

3


In [216]:
#KeyError

#Occurs when dictionary key does not exist.

student = {
    "name": "Aman"
}

print(student["marks"])

KeyError: 'marks'

In [217]:
#Correct Code
print(student.get("marks"))

None


In [218]:
#ZeroDivisionError

#Occurs when dividing by zero.

print(10 / 0)

ZeroDivisionError: division by zero

In [219]:
#AttributeError

#Occurs when object has no attribute.

text = "Python"

text.append("AI")

AttributeError: 'str' object has no attribute 'append'

In [220]:
#ModuleNotFoundError

#Occurs when module does not exist.

import tensorflowxyz

ModuleNotFoundError: No module named 'tensorflowxyz'

In [ ]:
#FileNotFoundError

#Occurs when file does not exist.

file = open("abc.txt", "r")

In [221]:
#OverflowError

#Occurs when result is too large.

import math

print(math.exp(1000))

OverflowError: math range error

In [ ]:
#AssertionError

#Occurs when assert statement fails.

x = -5

assert x > 0

In [222]:
#StopIteration

#Occurs in iterators.

numbers = iter([1,2])

print(next(numbers))
print(next(numbers))
print(next(numbers))

1
2


StopIteration: 

In [ ]:
#ConnectionError

#Occurs in networking.

import requests

requests.get("http://wrongurl")

3. LOGICAL ERRORS
Program runs but output is wrong.


In [223]:
length = 10
breadth = 5

area = length + breadth

print(area)

15


In [224]:
#Wrong Condition
age = 15

if age > 18:
    print("Teenager")

## NUMPY

In [228]:
import numpy as np
import time

# =========================
# 1. Array Basics
# =========================

# 1D Array
arr = np.array([1, 2, 3, 4, 5])
print("1D Array:")
print(arr)

# 2D Array
matrix = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
print("\n2D Array:")
print(matrix)

# 3D Array
arr3d = np.array([
    [
        [1, 2],
        [3, 4]
    ],
    [
        [5, 6],
        [7, 8]
    ]
])
print("\n3D Array:")
print(arr3d)

# Check Array Type
arr = np.array([1, 2, 3])
print("\nType:")
print(type(arr))

# Check Dimensions
arr = np.array([[1, 2], [3, 4]])
print("\nDimensions:")
print(arr.ndim)

# Check Shape
arr = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
print("\nShape:")
print(arr.shape)

# Check Size
arr = np.array([[1, 2], [3, 4]])
print("\nSize:")
print(arr.size)

# Check Data Type
arr = np.array([1, 2, 3])
print("\nData Type:")
print(arr.dtype)

# =========================
# 2. Array Creation Functions
# =========================

print("\nZeros:")
print(np.zeros((3, 3)))

print("\nOnes:")
print(np.ones((2, 4)))

print("\nFull:")
print(np.full((2, 2), 7))

print("\nIdentity Matrix:")
print(np.eye(3))

print("\nArange:")
print(np.arange(1, 10, 2))

print("\nLinspace:")
print(np.linspace(0, 1, 5))

print("\nRandom Array:")
print(np.random.rand(3, 3))

print("\nRandom Integers:")
print(np.random.randint(1, 100, (3, 3)))

# =========================
# 3. Indexing & Slicing
# =========================

arr = np.array([10, 20, 30, 40])

print("\nIndexing:")
print(arr[0])
print(arr[-1])

arr = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

print("\n2D Indexing:")
print(arr[1, 2])

arr = np.array([1, 2, 3, 4, 5])

print("\nSlicing:")
print(arr[1:4])

arr = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

print("\n2D Slicing:")
print(arr[0:2, 1:3])

arr = np.array([10, 20, 30, 40])

print("\nBoolean Indexing:")
print(arr[arr > 20])

print("\nFancy Indexing:")
print(arr[[0, 2]])

# =========================
# 4. Array Operations
# =========================

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print("\nAddition:")
print(a + b)

print("\nSubtraction:")
print(a - b)

print("\nMultiplication:")
print(a * b)

print("\nDivision:")
print(a / b)

print("\nPower:")
print(a ** 2)

print("\nSquare Root:")
print(np.sqrt(a))

print("\nExponential:")
print(np.exp(a))

print("\nLogarithm:")
print(np.log(a))

angles = np.array([0, np.pi / 2])

print("\nSin:")
print(np.sin(angles))

print("\nCos:")
print(np.cos(angles))

# =========================
# 5. Statistical Operations
# =========================

arr = np.array([1, 2, 3, 4])

print("\nSum:", np.sum(arr))
print("Mean:", np.mean(arr))
print("Median:", np.median(arr))
print("Std:", np.std(arr))
print("Variance:", np.var(arr))
print("Min:", np.min(arr))
print("Max:", np.max(arr))
print("Argmax:", np.argmax(arr))
print("Argmin:", np.argmin(arr))

# =========================
# 6. Reshaping Arrays
# =========================

arr = np.array([1, 2, 3, 4, 5, 6])

print("\nReshape:")
print(arr.reshape(2, 3))

arr = np.array([
    [1, 2],
    [3, 4]
])

print("\nFlatten:")
print(arr.flatten())

print("\nRavel:")
print(arr.ravel())

print("\nTranspose:")
print(arr.T)

# =========================
# 7. Joining Arrays
# =========================

a = np.array([1, 2])
b = np.array([3, 4])

print("\nConcatenate:")
print(np.concatenate((a, b)))

print("\nVStack:")
print(np.vstack((a, b)))

print("\nHStack:")
print(np.hstack((a, b)))

arr = np.array([1, 2, 3, 4, 5, 6])

print("\nSplit:")
print(np.split(arr, 3))

# =========================
# 8. Broadcasting
# =========================

arr = np.array([1, 2, 3])

print("\nBroadcasting:")
print(arr + 10)

matrix = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

print("\nBroadcast Matrix:")
print(matrix + np.array([1, 1, 1]))

# =========================
# 9. Copy vs View
# =========================

arr = np.array([1, 2, 3])

copy_arr = arr.copy()
arr[0] = 100

print("\nCopy:")
print(copy_arr)

arr = np.array([1, 2, 3])

view_arr = arr.view()
arr[0] = 100

print("\nView:")
print(view_arr)

# =========================
# 10. Matrix Operations
# =========================

a = np.array([
    [1, 2],
    [3, 4]
])

b = np.array([
    [5, 6],
    [7, 8]
])

print("\nMatrix Multiplication:")
print(np.dot(a, b))

print("\nDeterminant:")
print(np.linalg.det(a))

print("\nInverse:")
print(np.linalg.inv(a))

values, vectors = np.linalg.eig(a)

print("\nEigen Values:")
print(values)

# =========================
# 11. Linear Algebra
# =========================

A = np.array([
    [2, 1],
    [1, 1]
])

B = np.array([5, 3])

solution = np.linalg.solve(A, B)

print("\nSolution:")
print(solution)

# =========================
# 12. Random Module
# =========================

np.random.seed(42)

print("\nRandom:")
print(np.random.rand(3))

print("\nRandom Choice:")
print(np.random.choice([10, 20, 30], size=5))

arr = np.array([1, 2, 3, 4, 5])

np.random.shuffle(arr)

print("\nShuffle:")
print(arr)

# =========================
# 13. Performance
# =========================

start = time.time()

a = list(range(100000))
b = list(range(100000))

c = [a[i] + b[i] for i in range(len(a))]

print("\nPython Time:", time.time() - start)

start = time.time()

a = np.arange(100000)
b = np.arange(100000)

c = a + b

print("NumPy Time:", time.time() - start)

# =========================
# 14. Missing Values
# =========================

arr = np.array([1, 2, np.nan, 4])

print("\nIs NaN:")
print(np.isnan(arr))

print("NaN Mean:")
print(np.nanmean(arr))

# =========================
# 15. Save & Load
# =========================

arr = np.array([1, 2, 3])

np.save("data.npy", arr)

data = np.load("data.npy")

print("\nLoaded NPY:")
print(data)

np.savetxt("data.csv", arr, delimiter=",")

data = np.loadtxt("data.csv", delimiter=",")

print("\nLoaded CSV:")
print(data)

# =========================
# 16. Real-Time Examples
# =========================

marks = np.array([85, 90, 78, 92, 88])

print("\nStudent Marks")
print("Average:", np.mean(marks))
print("Highest:", np.max(marks))
print("Lowest:", np.min(marks))

sales = np.array([1000, 2000, 1500, 3000])

growth = sales * 1.10

print("\nSales Growth:")
print(growth)

image = np.random.randint(0, 255, (3, 3))

print("\nImage Matrix:")
print(image)

1D Array:
[1 2 3 4 5]

2D Array:
[[1 2 3]
 [4 5 6]]

3D Array:
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]

Type:
<class 'numpy.ndarray'>

Dimensions:
2

Shape:
(2, 3)

Size:
4

Data Type:
int64

Zeros:
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

Ones:
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]

Full:
[[7 7]
 [7 7]]

Identity Matrix:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

Arange:
[1 3 5 7 9]

Linspace:
[0.   0.25 0.5  0.75 1.  ]

Random Array:
[[0.79294737 0.42951663 0.6285793 ]
 [0.23742611 0.2329226  0.44902614]
 [0.67389582 0.05472321 0.09262935]]

Random Integers:
[[20  1 35]
 [48 99 63]
 [20 50 40]]

Indexing:
10
40

2D Indexing:
6

Slicing:
[2 3 4]

2D Slicing:
[[2 3]
 [5 6]]

Boolean Indexing:
[30 40]

Fancy Indexing:
[10 30]

Addition:
[5 7 9]

Subtraction:
[-3 -3 -3]

Multiplication:
[ 4 10 18]

Division:
[0.25 0.4  0.5 ]

Power:
[1 4 9]

Square Root:
[1.         1.41421356 1.73205081]

Exponential:
[ 2.71828183  7.3890561  20.08553692]

Logarithm:
[0.         0.69314718 1.09861229]

Sin:
[0. 1.]

Cos:
